# Generated by Django 5.2.9 on 2025-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_rename_summary_resume_experience_resume_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hobbies',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
