# Generated by Django 5.2.9 on 2025-12-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_resume_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='acknowledgment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
