# Generated by Django 5.2.9 on 2025-12-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_resume_acknowledgment_resume_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.CharField(default='', max_length=200),
        ),
    ]
